create table Payroll (
	userid INT,
	name VARCHAR(50),
	job VARCHAR(50),
	salary INT,
	email VARCHAR(50)
);
insert into Payroll (userid, name, job, salary, email) values (1, 'Tamarra', 'Food Chemist', 194456, 'tgudd0@clickbank.net');
insert into Payroll (userid, name, job, salary, email) values (2, 'Van', 'Clinical Specialist', 73000, 'venrico1@istockphoto.com');
insert into Payroll (userid, name, job, salary, email) values (3, 'Jess', 'Software Test Engineer I', 221585, 'jcaurah2@hp.com');
insert into Payroll (userid, name, job, salary, email) values (4, 'Eleanore', 'Design Engineer', 209009, 'ebaxstar3@japanpost.jp');
insert into Payroll (userid, name, job, salary, email) values (5, 'Guglielma', 'Marketing Assistant', 86625, null);
insert into Payroll (userid, name, job, salary, email) values (6, 'Malva', 'Quality Control Specialist', 235151, null);
insert into Payroll (userid, name, job, salary, email) values (7, 'Giuseppe', 'Sales Associate', 129246, 'ggatchel6@sciencedirect.com');
insert into Payroll (userid, name, job, salary, email) values (8, 'Abra', 'Assistant Manager', 130216, 'amorrilly7@bbc.co.uk');
insert into Payroll (userid, name, job, salary, email) values (9, 'Sabina', 'VP Marketing', 57998, 'srichin8@usa.gov');
insert into Payroll (userid, name, job, salary, email) values (10, 'Burk', 'Developer IV', 151830, 'bbruckner9@artisteer.com');
insert into Payroll (userid, name, job, salary, email) values (11, 'Brucie', 'Senior Financial Analyst', 239189, null);
insert into Payroll (userid, name, job, salary, email) values (12, 'Jilli', 'Professor', 16270, 'jrickettsb@time.com');
insert into Payroll (userid, name, job, salary, email) values (13, 'Efren', 'Registered Nurse', 105573, 'ediamantc@whitehouse.gov');
insert into Payroll (userid, name, job, salary, email) values (14, 'Ernie', 'Legal Assistant', 44253, 'epiddocked@storify.com');
insert into Payroll (userid, name, job, salary, email) values (15, 'Lucian', 'Staff Accountant III', 72933, 'lwindmille@tripod.com');
insert into Payroll (userid, name, job, salary, email) values (16, 'Ethelyn', 'Administrative Officer', 139367, 'eodoghertyf@digg.com');
insert into Payroll (userid, name, job, salary, email) values (17, 'Dore', 'Registered Nurse', 169068, null);
insert into Payroll (userid, name, job, salary, email) values (18, 'Wallie', 'Web Developer III', 128058, 'wworkesh@pcworld.com');
insert into Payroll (userid, name, job, salary, email) values (19, 'Tersina', 'Sales Associate', 184799, null);
insert into Payroll (userid, name, job, salary, email) values (20, 'Aguste', 'Financial Advisor', 137243, 'ahaslehurstj@phpbb.com');
insert into Payroll (userid, name, job, salary, email) values (21, 'Farrell', 'Senior Sales Associate', 127707, 'fextilk@list-manage.com');
insert into Payroll (userid, name, job, salary, email) values (22, 'Ranice', 'Payment Adjustment Coordinator', 57793, null);
insert into Payroll (userid, name, job, salary, email) values (23, 'Lombard', 'Marketing Assistant', 90834, null);
insert into Payroll (userid, name, job, salary, email) values (24, 'Ches', 'Engineer II', 78181, null);
insert into Payroll (userid, name, job, salary, email) values (25, 'Flossie', 'Legal Assistant', 53530, null);
insert into Payroll (userid, name, job, salary, email) values (26, 'Morlee', 'Tax Accountant', 206989, null);
insert into Payroll (userid, name, job, salary, email) values (27, 'Dell', 'Clinical Specialist', 115937, 'dtremonteq@blogtalkradio.com');
insert into Payroll (userid, name, job, salary, email) values (28, 'Kareem', 'Automation Specialist I', 34924, 'kwhitearr@wikipedia.org');
insert into Payroll (userid, name, job, salary, email) values (29, 'Yancey', 'Web Developer IV', 206288, 'yboundleys@canalblog.com');
insert into Payroll (userid, name, job, salary, email) values (30, 'Craggie', 'Registered Nurse', 209313, null);
insert into Payroll (userid, name, job, salary, email) values (31, 'Denyse', 'Associate Professor', 11020, 'dhebbleu@ycombinator.com');
insert into Payroll (userid, name, job, salary, email) values (32, 'Lissi', 'Nurse Practicioner', 174566, 'laneleyv@nytimes.com');
insert into Payroll (userid, name, job, salary, email) values (33, 'Kirby', 'Internal Auditor', 128339, null);
insert into Payroll (userid, name, job, salary, email) values (34, 'Chauncey', 'Administrative Officer', 150317, 'cpostonx@vimeo.com');
insert into Payroll (userid, name, job, salary, email) values (35, 'Darlleen', 'Dental Hygienist', 142648, 'djaycoxy@amazon.co.jp');
insert into Payroll (userid, name, job, salary, email) values (36, 'Ciro', 'Geologist I', 27220, 'ccundictz@illinois.edu');
insert into Payroll (userid, name, job, salary, email) values (37, 'Carolyne', 'Geological Engineer', 171740, 'ccrossman10@deliciousdays.com');
insert into Payroll (userid, name, job, salary, email) values (38, 'Jeremiah', 'Computer Systems Analyst II', 22442, null);
insert into Payroll (userid, name, job, salary, email) values (39, 'Raleigh', 'Account Representative IV', 98522, 'rdury12@dyndns.org');
insert into Payroll (userid, name, job, salary, email) values (40, 'Lovell', 'Computer Systems Analyst II', 109787, 'lebbing13@noaa.gov');
insert into Payroll (userid, name, job, salary, email) values (41, 'Hamel', 'Electrical Engineer', 131175, null);
insert into Payroll (userid, name, job, salary, email) values (42, 'Lamar', 'Sales Representative', 135851, null);
insert into Payroll (userid, name, job, salary, email) values (43, 'Dania', 'Assistant Manager', 115456, 'dyushkin16@auda.org.au');
insert into Payroll (userid, name, job, salary, email) values (44, 'Alexina', 'Biostatistician I', 123761, 'awaywell17@ihg.com');
insert into Payroll (userid, name, job, salary, email) values (45, 'Templeton', 'Occupational Therapist', 105148, null);
insert into Payroll (userid, name, job, salary, email) values (46, 'Thedrick', 'VP Accounting', 166399, 'thowey19@go.com');
insert into Payroll (userid, name, job, salary, email) values (47, 'Vic', 'Accounting Assistant III', 112355, 'vdoelle1a@cafepress.com');
insert into Payroll (userid, name, job, salary, email) values (48, 'Ofilia', 'Safety Technician III', 114477, 'osamples1b@ucoz.com');
insert into Payroll (userid, name, job, salary, email) values (49, 'Mariele', 'Librarian', 74602, 'mtitmarsh1c@creativecommons.org');
insert into Payroll (userid, name, job, salary, email) values (50, 'Elianora', 'Web Developer IV', 209695, 'ehowison1d@oracle.com');
insert into Payroll (userid, name, job, salary, email) values (51, 'Rosemonde', 'Physical Therapy Assistant', 85504, 'rkeyme1e@google.de');
insert into Payroll (userid, name, job, salary, email) values (52, 'Benji', 'Safety Technician IV', 54023, 'brobilliard1f@typepad.com');
insert into Payroll (userid, name, job, salary, email) values (53, 'Sheilakathryn', 'Account Executive', 5398, 'syurmanovev1g@php.net');
insert into Payroll (userid, name, job, salary, email) values (54, 'Anica', 'Web Designer II', 117566, 'abrandel1h@scientificamerican.com');
insert into Payroll (userid, name, job, salary, email) values (55, 'Neille', 'Environmental Tech', 172112, 'ngillfillan1i@ucoz.ru');
insert into Payroll (userid, name, job, salary, email) values (56, 'Bambi', 'Financial Analyst', 197875, null);
insert into Payroll (userid, name, job, salary, email) values (57, 'Vance', 'Assistant Manager', 126102, null);
insert into Payroll (userid, name, job, salary, email) values (58, 'Gerry', 'Biostatistician II', 228709, 'gjura1l@usnews.com');
insert into Payroll (userid, name, job, salary, email) values (59, 'Talyah', 'VP Accounting', 98654, 'tbrassington1m@craigslist.org');
insert into Payroll (userid, name, job, salary, email) values (60, 'Barnebas', 'Legal Assistant', 180251, 'bramme1n@princeton.edu');
insert into Payroll (userid, name, job, salary, email) values (61, 'Hamish', 'Administrative Assistant I', 121201, 'hlenz1o@mac.com');
insert into Payroll (userid, name, job, salary, email) values (62, 'Terri', 'Occupational Therapist', 193382, 'thatrick1p@furl.net');
insert into Payroll (userid, name, job, salary, email) values (63, 'Nanette', 'Director of Sales', 189191, 'nfarfalameev1q@mysql.com');
insert into Payroll (userid, name, job, salary, email) values (64, 'Querida', 'Legal Assistant', 152247, 'qcabane1r@ucla.edu');
insert into Payroll (userid, name, job, salary, email) values (65, 'Slade', 'Account Representative IV', 107831, null);
insert into Payroll (userid, name, job, salary, email) values (66, 'Rand', 'Design Engineer', 69544, null);
insert into Payroll (userid, name, job, salary, email) values (67, 'Virgie', 'Desktop Support Technician', 123620, 'vkellaway1u@accuweather.com');
insert into Payroll (userid, name, job, salary, email) values (68, 'Jordon', 'Research Associate', 25654, 'jsturge1v@freewebs.com');
insert into Payroll (userid, name, job, salary, email) values (69, 'Prince', 'Cost Accountant', 95613, 'pjackalin1w@cbc.ca');
insert into Payroll (userid, name, job, salary, email) values (70, 'Georgeanne', 'Senior Editor', 236854, 'ggunby1x@addtoany.com');
insert into Payroll (userid, name, job, salary, email) values (71, 'Udall', 'Computer Systems Analyst III', 229311, 'ulambird1y@ustream.tv');
insert into Payroll (userid, name, job, salary, email) values (72, 'Eachelle', 'Geological Engineer', 190429, null);
insert into Payroll (userid, name, job, salary, email) values (73, 'Keri', 'Human Resources Manager', 8475, 'kgabbotts20@google.com.br');
insert into Payroll (userid, name, job, salary, email) values (74, 'Maudie', 'Junior Executive', 239998, 'mkubacki21@vimeo.com');
insert into Payroll (userid, name, job, salary, email) values (75, 'Brennan', 'VP Accounting', 239613, 'bsurplice22@oracle.com');
insert into Payroll (userid, name, job, salary, email) values (76, 'Major', 'Financial Advisor', 153501, 'mbanger23@tripod.com');
insert into Payroll (userid, name, job, salary, email) values (77, 'Cleve', 'Data Coordiator', 115105, 'cmaskall24@fc2.com');
insert into Payroll (userid, name, job, salary, email) values (78, 'Emlen', 'Administrative Officer', 100457, 'efivey25@hatena.ne.jp');
insert into Payroll (userid, name, job, salary, email) values (79, 'Mikaela', 'Recruiter', 11224, 'mbullen26@live.com');
insert into Payroll (userid, name, job, salary, email) values (80, 'Leia', 'Legal Assistant', 59646, 'lhazeldine27@storify.com');
insert into Payroll (userid, name, job, salary, email) values (81, 'Zondra', 'Help Desk Operator', 211348, 'zsilverson28@yahoo.co.jp');
insert into Payroll (userid, name, job, salary, email) values (82, 'Rosalinda', 'Business Systems Development Analyst', 219879, 'rshearer29@technorati.com');
insert into Payroll (userid, name, job, salary, email) values (83, 'Evyn', 'Compensation Analyst', 29734, null);
insert into Payroll (userid, name, job, salary, email) values (84, 'Reg', 'Programmer Analyst I', 210815, 'rsworder2b@example.com');
insert into Payroll (userid, name, job, salary, email) values (85, 'Austina', 'Budget/Accounting Analyst III', 242424, null);
insert into Payroll (userid, name, job, salary, email) values (86, 'Annecorinne', 'Social Worker', 85265, null);
insert into Payroll (userid, name, job, salary, email) values (87, 'Allyn', 'Nurse Practicioner', 166461, 'acockney2e@list-manage.com');
insert into Payroll (userid, name, job, salary, email) values (88, 'Codie', 'Legal Assistant', 159066, 'cogdahl2f@ox.ac.uk');
insert into Payroll (userid, name, job, salary, email) values (89, 'Hyatt', 'Clinical Specialist', 194368, 'hkender2g@tripod.com');
insert into Payroll (userid, name, job, salary, email) values (90, 'Carmina', 'Quality Control Specialist', 169100, 'cturbern2h@ocn.ne.jp');
insert into Payroll (userid, name, job, salary, email) values (91, 'Sydel', 'Graphic Designer', 114123, null);
insert into Payroll (userid, name, job, salary, email) values (92, 'Van', 'VP Quality Control', 166402, 'vmccobb2j@state.tx.us');
insert into Payroll (userid, name, job, salary, email) values (93, 'Zorah', 'Staff Accountant II', 137562, null);
insert into Payroll (userid, name, job, salary, email) values (94, 'Magdalene', 'Assistant Manager', 147705, null);
insert into Payroll (userid, name, job, salary, email) values (95, 'Laney', 'Clinical Specialist', 100446, null);
insert into Payroll (userid, name, job, salary, email) values (96, 'Bowie', 'Professor', 93795, null);
insert into Payroll (userid, name, job, salary, email) values (97, 'Billye', 'Programmer III', 110915, 'bfoston2o@foxnews.com');
insert into Payroll (userid, name, job, salary, email) values (98, 'Reggie', 'Office Assistant IV', 221019, null);
insert into Payroll (userid, name, job, salary, email) values (99, 'Ozzie', 'Nuclear Power Engineer', 130433, 'ocloke2q@usa.gov');
insert into Payroll (userid, name, job, salary, email) values (100, 'Arabel', 'Health Coach IV', 174610, 'amccarlie2r@google.com.hk');
